// Dân tộc Việt Nam theo danh mục TĐT 2019
export const ETHNICITY_TYPES = {
  KINH: 'Kinh',
  TAY: 'Tày',
  THAI: 'Thái',
  HOA: 'Hoa',
  KHMER: 'Khmer',
  MUONG: 'Mường',
  NUNG: 'Nùng',
  MONG: 'Mông',
  DAO: 'Dao',
  GIA_RAI: 'Gia Rai',
  NGAI: 'Ngái',
  E_DE: 'Ê Đê',
  BA_NA: 'Ba Na',
  XO_DANG: 'Xơ Đăng',
  SAN_CHAY: 'Sán Chay',
  CO_HO: 'Cơ Ho',
  CHAM: 'Chăm',
  SAN_DIU: 'Sán Dìu',
  HRE: 'Hrê',
  MNONG: 'Mnông',
  RAGLAY: 'Raglay',
  XTIENG: 'Xtiêng',
  BRU_VAN_KIEU: 'Bru - Vân Kiều',
  THO: 'Thổ',
  GIAY: 'Giáy',
  CO_TU: 'Cơ Tu',
  GIE_TRIENG: 'Gié Triêng',
  MA: 'Mạ',
  KHO_MU: 'Khơ mú',
  CO: 'Co',
  TA_OI: 'Tà Ôi',
  CHO_RO: 'Chơ Ro',
  KHANG: 'Kháng',
  XINH_MUN: 'Xinh Mun',
  HA_NHI: 'Hà Nhì',
  CHU_RU: 'Chu Ru',
  LAO: 'Lào',
  LA_CHI: 'La Chí',
  LA_HA: 'La Ha',
  PHU_LA: 'Phù Lá',
  LA_HU: 'La Hủ',
  LU: 'Lự',
  LO_LO: 'Lô Lô',
  CHUT: 'Chứt',
  MANG: 'Mảng',
  PA_THEN: 'Pà Thẻn',
  CO_LAO: 'Cơ Lao',
  CONG: 'Cống',
  BO_Y: 'Bố Y',
  SI_LA: 'Si La',
  PU_PEO: 'Pu Péo',
  BRAU: 'Brâu',
  O_DU: 'Ơ Đu',
  RO_MAM: 'Rơ Măm',
  FOREIGNER: 'Người nước ngoài',
  UNDEFINED: 'Không xác định',
} as const;

export type Ethnicity = (typeof ETHNICITY_TYPES)[keyof typeof ETHNICITY_TYPES];
