import { EXAM_STATUS, ExamStatus } from "./exam-status.enum";

export const EXAMINEE_STAGES = {
  REGISTRATION: 0,
  TOPIC: 1,
  EDUCATION: 2,
  SCHEDULE: 3,
  RESULT: 4,
  FINISH: 5,
} as const;

export type ExamineeStage =
  (typeof EXAMINEE_STAGES)[keyof typeof EXAMINEE_STAGES];

export const EXAMINEE_STAGE_LABELS: Record<ExamineeStage, string> = {
  [EXAMINEE_STAGES.REGISTRATION]: "Đăng Ký Thi",
  [EXAMINEE_STAGES.TOPIC]: "Đề Tài",
  [EXAMINEE_STAGES.EDUCATION]: "Đào Tạo",
  [EXAMINEE_STAGES.SCHEDULE]: "Tổ Chức Thi",
  [EXAMINEE_STAGES.RESULT]: "Nhập Kết Quả",
  [EXAMINEE_STAGES.FINISH]: "Hoàn thành",
};

export const EXAM_STATUS_TO_STAGE_MAPPER: Record<ExamStatus, ExamineeStage> = {
  [EXAM_STATUS.DRAFT]: EXAMINEE_STAGES.REGISTRATION,
  [EXAM_STATUS.REGISTRATION]: EXAMINEE_STAGES.REGISTRATION,
  [EXAM_STATUS.REVIEW]: EXAMINEE_STAGES.REGISTRATION,
  [EXAM_STATUS.APPROVED]: EXAMINEE_STAGES.REGISTRATION,
  [EXAM_STATUS.TOPIC_REGISTRATION]: EXAMINEE_STAGES.TOPIC,
  [EXAM_STATUS.TOPIC_APPROVED]: EXAMINEE_STAGES.TOPIC,
  [EXAM_STATUS.EDUCATION_RESULT]: EXAMINEE_STAGES.EDUCATION,
  [EXAM_STATUS.EXAM]: EXAMINEE_STAGES.SCHEDULE,
  [EXAM_STATUS.ENTER_RESULT]: EXAMINEE_STAGES.RESULT,
  [EXAM_STATUS.ENTER_DECISION]: EXAMINEE_STAGES.RESULT,
  [EXAM_STATUS.COMPLETED]: EXAMINEE_STAGES.FINISH,
};
